descriptionFormat: '{product.title} - {title}'
handle: bike
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
hasVariants: true
name: Bike
productFieldLayouts:
  8104fb3b-ffde-4282-993b-2d27a7bc6bd5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 70ff1d0c-40d7-4391-aa71-421eae489ddb
            warning: null
            width: 100
          -
            fieldUid: 86ec2b26-5d53-4798-8fb0-927890e52039 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46532c77-b96b-4cf0-9b90-c26645cb403a
            warning: null
            width: 100
          -
            fieldUid: 19549c94-cebb-4606-a533-aaef9dc49de7 # Geometry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05beaa0f-a0f2-4d59-ac5c-18a84db6526f
            warning: null
            width: 100
          -
            fieldUid: 5f3f9d21-e4a4-40d6-b80f-a92d99e02926 # Show Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 908ddd31-9756-4c37-a746-1c1899c54706
            warning: null
            width: 100
        name: Content
        uid: c533dded-0edb-4b1d-8807-0e2973485136
      -
        elements:
          -
            fieldUid: 5572edd6-3495-4a53-8f09-68bb6c53d79a # Main Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f30d77c0-43c6-4a76-8f15-ff62429e0137
            warning: null
            width: 100
          -
            fieldUid: 705abccb-1d21-44fe-a3f7-87530e29cd34 # Product Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4869b233-0b0b-4315-a9d2-db27707adad9
            warning: null
            width: 100
        name: Images
        uid: b249908c-82af-4b9b-8dd6-051039531757
      -
        elements:
          -
            fieldUid: f3de475b-4a85-4e74-b144-4ff3e464f057 # Bike Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f26e813e-4219-44eb-bf0e-5574c0dab304
            warning: null
            width: 100
          -
            fieldUid: 06e900c5-0757-485f-bda2-2875772bbe25 # Colors
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22191898-d14f-4b7a-a9b9-37addf22ca05
            warning: null
            width: 100
          -
            fieldUid: 03b7bc53-c8e9-48e4-8f45-da16de73909b # Material
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94839541-5923-4fc2-a1f7-582769b3fb80
            warning: null
            width: 100
        name: Options
        uid: 52d8a48c-9803-4731-baa1-fb190cdf6250
      -
        elements:
          -
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: bd670d41-9084-4f38-81d1-52af456549f9
            warning: null
        name: Variants
        uid: 2098ddec-442a-4b65-9f97-3e2c3687df08
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae52e449-2619-4e43-ac00-2185dd3a3b46
            warning: null
            width: 100
        name: SEO
        uid: 8884bdcc-7a75-466d-a9ef-421c714bd561
productTitleFormat: ''
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    hasUrls: true
    template: _views/products/bike
    uriFormat: 'product/{slug}'
skuFormat: ''
variantFieldLayouts:
  7480375f-d72f-4bf8-806a-2c72045b9880:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: d8a0e678-0c31-41f0-a269-c625e121bef2
            warning: null
            width: 100
        name: Content
        uid: de6cef88-f6ea-47e4-87e6-6d8eac64fced
variantTitleFormat: '{product.title}'
