field: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
fieldLayouts:
  3474d9f8-95a1-4792-b81f-3c0cfd36d4ce:
    tabs:
      -
        elements:
          -
            fieldUid: 4618ebbc-ed9f-4632-8648-dbbfafc12ce5 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4b80906-211e-4a73-bb42-6a172d0f5a2d
            warning: null
            width: 100
          -
            fieldUid: 520350fa-6eaf-4bc0-9568-687055d5b462 # Form
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a399492c-820b-4dc7-8f7f-a353553af6f0
            warning: null
            width: 100
        name: Content
        uid: e78c05ce-8a3e-49f6-b8c9-6cac8ed1041f
fields:
  4618ebbc-ed9f-4632-8648-dbbfafc12ce5: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Enter an optional heading to be displayed above the form.'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  520350fa-6eaf-4bc0-9568-687055d5b462: # Form
    columnSuffix: null
    contentColumnType: integer
    fieldGroup: null
    handle: form
    instructions: 'Choose the form you’d like to display on this page.'
    name: Form
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: Solspace\Freeform\FieldTypes\FormFieldType
handle: form
name: Form
sortOrder: 4
