field: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
fieldLayouts:
  bd5cdfbd-9eb4-42c1-a500-37732ab3f1c7:
    tabs:
      -
        elements:
          -
            fieldUid: d6666f58-4d11-4bd3-b5bd-bc92b52a538c # Products
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 015c4ed4-a885-4b10-8745-846ed8cabaa9
            warning: null
            width: 100
        name: Content
        uid: bbacd397-59ce-4f89-8650-1a69cc0404b8
fields:
  d6666f58-4d11-4bd3-b5bd-bc92b52a538c: # Products
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: products
    instructions: 'Select up to three products to promote.'
    name: Products
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 3
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\commerce\fields\Products
handle: products
name: Products
sortOrder: 3
