fieldLayouts:
  2ac896d4-c65e-4d74-b4ec-f26cf1d3053d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d44bdee3-b69a-41b5-acc7-e98e9c47d2f6
            warning: null
            width: 100
          -
            fieldUid: 5572edd6-3495-4a53-8f09-68bb6c53d79a # Main Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b12f8c7-a69c-4f35-9ced-180ea8c36f00
            warning: null
            width: 100
        name: Content
        uid: d497cbe8-be16-468d-917a-5a62b44ec85c
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 43693437-55b4-42fe-bd32-e80bcdcf77ae
            warning: null
            width: 100
          -
            fieldUid: 5572edd6-3495-4a53-8f09-68bb6c53d79a # Main Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f08c1b9-52e7-4d9a-b3f1-ed3f4e15cdc3
            warning: null
            width: 100
        name: Content
        uid: a8d80af2-c512-4a5f-bc41-86abaa6657ce
handle: bikesLanding
hasTitleField: false
name: Bikes
section: 384841aa-9783-4efd-a81f-0f4aa159ab33 # Bikes
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
