fieldLayouts:
  d6bab467-3ac2-4092-9bf6-30c86263d0c5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4f82ac40-279f-4880-9c13-a234dd5d566a
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ffd9a38-ec71-4bc3-a6cf-097f04262123
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed19020b-94a5-47b7-b656-87ad9ee1bc10
            warning: null
            width: 100
          -
            fieldUid: 86ec2b26-5d53-4798-8fb0-927890e52039 # Body
            instructions: null
            label: 'No items content'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cfb65a1-864b-45b4-8cad-986b0c11177b
            warning: null
            width: 100
        name: Content
        uid: 0162ec3a-312a-408a-94b3-de147b30c96c
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 24320b5c-e5d9-442c-b34c-79c34a80b9b5
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cd2c347-3509-47d1-8fb3-11a2eb7ad7a9
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c12455ff-5401-4b9a-9cdc-660a3f229470
            warning: null
            width: 100
          -
            fieldUid: 86ec2b26-5d53-4798-8fb0-927890e52039 # Body
            instructions: null
            label: 'No items content'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc23a811-65c2-43f0-b556-eb3841ea389e
            warning: null
            width: 100
        name: Content
        uid: 736ca1f0-e8f0-4e57-99cc-5d630da1421b
handle: cart
hasTitleField: true
name: Cart
section: 7e2085d8-34c4-41a9-81fc-db0fef15293f # Cart
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
