fieldLayouts:
  f8853b83-c030-4ebe-896c-e344ed6abef0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 123b5d5f-9c86-4dcf-a9f9-be3a93a2678c
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9028308-21e8-427b-a618-f7079cfbcb4a
            warning: null
            width: 100
        name: Content
        uid: ccb8fadb-3e25-484b-9d44-ef87473cf07a
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 77c99a1e-2517-41df-a064-87aacba513ea
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8327069b-6049-4557-a228-7335edd7a7ec
            warning: null
            width: 100
        name: Content
        uid: 1dbd69a5-5f4a-4a9e-8fbc-802747556860
handle: checkoutSummary
hasTitleField: true
name: 'Checkout: Summary'
section: 58f90099-0367-42d6-a8e0-076eab66373b # Checkout: Summary
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
