fieldLayouts:
  f8853b83-c030-4ebe-896c-e344ed6abef0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2c4fb81b-4edc-435d-818f-63a415e5bf45
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9e645a8-761e-4380-afa9-dba95fc104b5
            warning: null
            width: 100
        name: Content
        uid: ccb8fadb-3e25-484b-9d44-ef87473cf07a
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5ae878d9-64b2-4871-8937-b1175cad4df2
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eeb9916b-4462-46d5-b6ba-78e23cffd17b
            warning: null
            width: 100
        name: Content
        uid: 1dbd69a5-5f4a-4a9e-8fbc-802747556860
handle: checkoutSummary
hasTitleField: true
name: 'Checkout: Summary'
section: 58f90099-0367-42d6-a8e0-076eab66373b # Checkout: Summary
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
