fieldLayouts:
  482c524a-895e-47e5-a80b-22ef6f7a2bd1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 991a8844-258a-4fa3-abf5-d5f346ec2feb
            warning: null
            width: 100
        name: Content
        uid: 97565aa9-8dbf-4c2d-89ba-3b6ee08bfe63
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 68670cc2-615e-431c-824c-9d99e3827cd2
            warning: null
            width: 100
        name: Content
        uid: b1c5ca0f-1d44-4d7c-8e68-dd26dbcaa246
handle: checkoutShipping
hasTitleField: true
name: 'Checkout: Shipping'
section: 92145d02-d68b-4c71-a8be-fa082467d8fc # Checkout: Shipping
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
