fieldLayouts:
  26ba6c2d-9984-4cee-827b-6a35223f1d16:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bf86a5e2-6457-4960-b85b-4f2c2d485db5
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edcc0721-8113-4d16-b849-eef92b97d4f5
            warning: null
            width: 100
        name: Content
        uid: 03d19f7a-95a5-44f3-8107-79869d901ce8
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8245d53b-eb8e-46c6-81d8-c5010df19c33
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53514426-f62b-42c3-819e-e4ac1834ae8b
            warning: null
            width: 100
        name: Content
        uid: 88e9d9ba-cfd3-4da9-9b71-a018817b3f58
handle: contact
hasTitleField: false
name: Contact
section: 9b9e7f64-d3ac-4cd8-9ac6-2dad92ba68f1 # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
