fieldLayouts:
  26ba6c2d-9984-4cee-827b-6a35223f1d16:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 56bb7f77-d70b-4264-9c98-bc95f61bfe57
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19f00977-daee-4bb6-9ce7-e446a2c6a046
            warning: null
            width: 100
        name: Content
        uid: 03d19f7a-95a5-44f3-8107-79869d901ce8
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 06299850-579d-478f-85d8-423693c68b02
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3965c324-ee15-4dd5-bd1b-2045a22011ff
            warning: null
            width: 100
        name: Content
        uid: 88e9d9ba-cfd3-4da9-9b71-a018817b3f58
handle: contact
hasTitleField: false
name: Contact
section: 9b9e7f64-d3ac-4cd8-9ac6-2dad92ba68f1 # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
