fieldLayouts:
  508dee1a-a736-4ed5-a082-159858c9a490:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bd1a3cbe-6e5f-43ee-9e0b-542dd8dabdc1
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7a7da0a-db92-4ce8-b3a4-a5d57e387f0c
            warning: null
            width: 100
          -
            fieldUid: 86ec2b26-5d53-4798-8fb0-927890e52039 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01119307-7ff1-4d36-94ff-f305c60feea5
            warning: null
            width: 100
        name: Content
        uid: 02797761-7c41-4564-86b6-bc90b95ab36d
handle: emails
hasTitleField: true
name: Emails
section: 5075e975-0eb8-4e62-9ae7-9d8cd88348eb # Emails
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
