fieldLayouts:
  b0e6a962-9009-46e1-9c22-c30bc59b0daf:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 534f17f1-9a38-4b84-b575-cbcd4c9a80f8
            warning: null
            width: 100
          -
            fieldUid: d3fad61c-dfb9-4da2-bb75-6d2910c3c4ca # Plain Text 1
            instructions: null
            label: 'Forgot Password Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae5ea744-66b5-45ad-b4fa-4b95764f8e09
            warning: null
            width: 100
          -
            fieldUid: e60fd5c1-9f1b-496d-8369-a9daafcc185d # Plain Text 2
            instructions: null
            label: 'Register Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e761dad5-0137-4454-a317-a2c6384d6fec
            warning: null
            width: 100
        name: Content
        uid: bc24f0e0-1306-4518-a060-aa41a29d56a7
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5296cb3b-5c79-42ed-96de-c778a8642c38
            warning: null
            width: 100
          -
            fieldUid: d3fad61c-dfb9-4da2-bb75-6d2910c3c4ca # Plain Text 1
            instructions: null
            label: 'Forgot Password Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4617655a-e17c-4eb2-b774-4c8bd26bfcfd
            warning: null
            width: 100
          -
            fieldUid: e60fd5c1-9f1b-496d-8369-a9daafcc185d # Plain Text 2
            instructions: null
            label: 'Register Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2847aa17-99c2-47a0-b99c-6350f4a99d7f
            warning: null
            width: 100
        name: Content
        uid: 7ab70eab-b1f0-433a-b346-0a1733d81e24
handle: login
hasTitleField: true
name: Login
section: 21dd60d6-92a7-4e82-8884-7dbe57d73c6c # Account
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
