fieldLayouts:
  f5681def-99aa-4ac3-8696-1fb1135f4419:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f55c5060-1e30-47d0-aad0-8b076786db80
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab23d368-3d38-4c96-8b54-3d26eb6332ee
            warning: null
            width: 100
          -
            fieldUid: d3fad61c-dfb9-4da2-bb75-6d2910c3c4ca # Plain Text 1
            instructions: null
            label: 'Manage Membership Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 846cbbe8-0fdb-417e-8ed0-b9cb582046ac
            warning: null
            width: 100
          -
            fieldUid: e60fd5c1-9f1b-496d-8369-a9daafcc185d # Plain Text 2
            instructions: null
            label: 'View Memberships Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c6956a5-e272-4238-b0e5-4729196e3ef6
            warning: null
            width: 100
        name: Content
        uid: 252a5221-251c-4b43-b5a1-5a5c87e3b2c2
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 64baea74-419e-4062-839d-641043c0da16
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f6f8e44-89fc-4d9a-9ad8-9ceea665c76d
            warning: null
            width: 100
          -
            fieldUid: d3fad61c-dfb9-4da2-bb75-6d2910c3c4ca # Plain Text 1
            instructions: null
            label: 'Manage Membership Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e94601f5-9e43-48bc-a184-0151410cafe2
            warning: null
            width: 100
          -
            fieldUid: e60fd5c1-9f1b-496d-8369-a9daafcc185d # Plain Text 2
            instructions: null
            label: 'View Memberships Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bea31c55-0431-4bcd-a02e-d3e147023ad2
            warning: null
            width: 100
        name: Content
        uid: f9a5fad9-6b52-4eb9-8d8d-315bd647568e
handle: membership
hasTitleField: true
name: Membership
section: 21dd60d6-92a7-4e82-8884-7dbe57d73c6c # Account
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
