fieldLayouts:
  09f50636-036b-45fe-b573-04b734738d40:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b10360b9-7ae2-4e0d-b9a6-0fc80cc039a9
            warning: null
            width: 100
          -
            fieldUid: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 516665e2-98c4-4de7-90f0-47a71da397d2
            warning: null
            width: 100
        name: Content
        uid: abcfe95b-d96f-4aca-bf1f-a1cb0581ed26
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a8fb2d35-38b6-4440-95d2-356977c0d939
            warning: null
            width: 100
          -
            fieldUid: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acecb0ca-694d-47f2-b48f-f1a2cae455b6
            warning: null
            width: 100
        name: Content
        uid: ffd8fa2f-12c1-4a7b-8353-006593963c10
handle: page
hasTitleField: true
name: Page
section: 2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5 # Landing Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
