fieldLayouts:
  09f50636-036b-45fe-b573-04b734738d40:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d6b474bc-e070-4cca-b1ac-bb8e922af3a2
            warning: null
            width: 100
          -
            fieldUid: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 502df09a-7806-4d9a-865d-b509ef3a9667
            warning: null
            width: 100
        name: Content
        uid: abcfe95b-d96f-4aca-bf1f-a1cb0581ed26
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6cc905a0-8874-4b40-9d9c-5e6900cb493a
            warning: null
            width: 100
          -
            fieldUid: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8d681f4-3032-43bc-90d6-2cbe7a6df267
            warning: null
            width: 100
        name: Content
        uid: ffd8fa2f-12c1-4a7b-8353-006593963c10
handle: page
hasTitleField: true
name: Page
section: 2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5 # Landing Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
