fieldLayouts:
  2caa0b26-e0eb-49f6-8457-6f905d542b19:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e0f100b9-4d2d-4567-ada0-c763a3c1ca17
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a54d183e-7397-49c6-8552-fa4dbd27441e
            warning: null
            width: 100
          -
            fieldUid: 86ec2b26-5d53-4798-8fb0-927890e52039 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f4b3bf8-a3a3-4109-b6ea-13180aec6d8d
            warning: null
            width: 100
        name: Content
        uid: 49ec1351-cdf1-4cdb-9a30-2f5a77fa22c8
handle: pdfs
hasTitleField: true
name: PDFs
section: 220feec1-8cc9-4f3e-82da-73c748d0ae0b # PDFs
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
