fieldLayouts:
  1cc7f891-fbc6-4719-912c-584df79a6353:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ed042c5f-5b09-4c0d-a67d-7f456d0d9dc0
            warning: null
            width: 100
          -
            fieldUid: 86ec2b26-5d53-4798-8fb0-927890e52039 # Body
            instructions: null
            label: Review
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7bf1e07-c092-4642-888f-76ef52df6a54
            warning: null
            width: 100
          -
            fieldUid: cb3481b3-e34c-4104-b4da-6f86236f44ca # Product
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ac2c1ea-5d9a-4210-8998-e7d2dfec6f7a
            warning: null
            width: 100
          -
            fieldUid: fcaf6130-3481-4680-bf31-2ee9b178c554 # Stars
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71d9afb6-c8f9-4c74-9be4-24cbbdf75c6b
            warning: null
            width: 100
        name: Content
        uid: e4658e53-d171-4ffa-a1f0-330c1b32ae88
handle: reviews
hasTitleField: true
name: Reviews
section: 32faa6bc-a330-408a-b37a-4e8bde606b43 # Reviews
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
