fieldLayouts:
  f35f48a2-5520-4076-bee1-e1f5134c3145:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f225adaf-a4f9-4ac4-b600-67298caecf8f
            warning: null
            width: 100
          -
            fieldUid: 9b41a7f2-dc44-4ede-8931-b8f5895093f7 # Image Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64c5f71c-caed-4ebd-aa29-9b595ba4820c
            warning: null
            width: 100
          -
            fieldUid: ba0c0b5b-813d-4075-acec-9700550b80ae # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50fe7ed7-1628-41fb-8750-7b7aabb47144
            warning: null
            width: 100
        name: Content
        uid: 9c3beb08-c866-46f2-a01f-543085518767
fs: $FS_HANDLE
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
