columnSuffix: null
contentColumnType: string
handle: button
instructions: null
name: Button
searchable: false
settings:
  entryTypes:
    - 4735edf8-ae6c-4f28-a8df-338ca5637aab # Button
  maxEntries: 1
  minEntries: 0
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
