columnSuffix: pakraxun
contentColumnType: text
handle: imageCaption
instructions: 'Optionally write a brief caption to appear along with the image.'
name: 'Image Caption'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
