fieldLayouts:
  15235b15-7e3b-41db-9d9a-a8be850b6fc5:
    tabs:
      -
        elements:
          -
            fieldUid: 5572edd6-3495-4a53-8f09-68bb6c53d79a # Main Image
            instructions: 'Optionally designate a bike geometry reference to be displayed on relevant product detail pages.'
            label: 'Geometry Reference'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e8dee91-ffb3-478a-89fc-612e6f934711
            warning: null
            width: 100
        name: Products
        uid: fbfe9b99-ff8b-4143-b500-33906f29770b
handle: bikes
name: Bikes
sortOrder: 2
