fieldLayouts:
  d78ad337-2e0d-4308-a919-f3a76bee12e3:
    tabs:
      -
        elements:
          -
            fieldUid: 54f6a656-b4ef-4d80-86dc-2ed613f64056 # Business Hours
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d0cb93a-1a69-46ba-810d-fe72ba047f14
            warning: null
            width: 100
          -
            fieldUid: ea02150d-88e1-46f5-ab32-052940c08072 # Business Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99355b2e-4f96-44f8-8f3b-00feceaacd3d
            warning: null
            width: 100
        name: Content
        uid: 7d889504-d465-4e94-8d50-b604aa671bcd
handle: shop
name: Shop
sortOrder: 1
