defaultPlacement: end
enableVersioning: true
entryTypes:
  - 17eacd1a-f88d-4127-b328-9b69903624fc # Orders
  - 449f7b84-6b85-4caa-9b9e-1575953516a8 # Settings
  - 2170bde4-2ca6-4d6f-b2d0-7367050a564a # Membership
  - 21814db2-4816-41e4-bdc9-7d25e0869666 # Register
  - 938640bc-562a-4bde-9ab8-4c0b3489b21f # Login
  - f3c02b05-5d6b-423e-96b9-0071d0284f5b # Dashboard
handle: account
name: Account
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/account/index
    uriFormat: 'account/{slug}'
structure:
  maxLevels: 1
  uid: 3ed5e76d-6bdf-4c94-95ab-b7f24b1f1333
type: structure
