name: Update Dependencies

on:
  push:
    branches: [feature/dvo-126-auto-updatepr-bot-for-demos]
#  workflow_dispatch:
#    inputs:
#      name:
#        description: 'Person to greet'
#        required: true
#        default: 'Mona the Octocat'
#      home:
#        description: 'location'
#        required: false
#        default: 'The Octoverse'

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update depencencies
    steps:
      - uses: actions/checkout@v2

      - name: Update Composer & seed data
        run: make update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3